spring:
  application:
    name: customer-service
  cloud:
    stream:
      kafka:
        bindings:
          customer-out-0:
            producer:
              configuration:
                key:
                  serializer: org.apache.kafka.common.serialization.IntegerSerializer
                value:
                  serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
                  subject:
                    name:
                      strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
                schema:
                  registry:
                    url: http://localhost:8081
      bindings:
        customer-out-0:
          destination: customer
          producer:
            useNativeEncoding: true

server:
  port: 8084

